### ISSUE TITLE
Unable to get worker harness container image

### ISSUE THREAD

**Issue by jskontorp** [GoogleCloudPlatform/dataflow-geobeam#22]
Unable to get the worker harness container images used in the examples.

~~`➜  docker pull gcr.io/dataflow-geobeam/example-py37 `~~

~~`Using default tag: latest
Cannot connect to the Docker daemon at unix:///Users/jorgen.skontorp/.docker/run/docker.sock. Is the docker daemon running?`~~

~~`➜   docker pull gcr.io/dataflow-geobeam/base-py37`~~

~~`Using default tag: latest
Cannot connect to the Docker daemon at unix:///Users/jorgen.skontorp/.docker/run/docker.sock. Is the docker daemon running?`~~

~~`➜   docker pull gcr.io/dataflow-geobeam/example`~~

~~`Using default tag: latest
Cannot connect to the Docker daemon at unix:///Users/jorgen.skontorp/.docker/run/docker.sock. Is the docker daemon running?`~~

~~`➜   docker pull gcr.io/dataflow-geobeam/base`~~

~~`Using default tag: latest
Cannot connect to the Docker daemon at unix:///Users/jorgen.skontorp/.docker/run/docker.sock. Is the docker daemon running?`~~

```
➜ docker pull gcr.io/dataflow-geobeam/base
Using default tag: latest
Error response from daemon: manifest for gcr.io/dataflow-geobeam/base:latest not found: manifest unknown: Failed to fetch "latest" from request "/v2/dataflow-geobeam/base/manifests/latest"
```

**Comment by tjwebb** [comment]
Are you able to pull other docker images? It looks like you may need to fire up the docker engine before attempting to pull the images.

**Comment by jskontorp** [comment]
Yes, sorry I was a bit too fast posting this. Originally I was running a beam pipeline which failed with the following warning message:
```A worker was unable to start up.  Error: Unable to pull container image due to error: image pull request failed with error: Error response from daemon: manifest for gcr.io/dataflow-geobeam/example-py37:latest not found: manifest unknown: Failed to fetch "latest" from request "/v2/dataflow-geobeam/example-py37/manifests/latest".. This is likely due to an invalid SDK container image URL. Please verify any provided SDK container image is valid and that Dataflow workers have permissions to pull image.```

and then:

```Workflow failed. Causes: Job appears to be stuck. Several workers have failed to start up in a row, and no worker has successfully started up for this job. Last error reported: Unable to pull container image due to error: image pull request failed with error: Error response from daemon: manifest for gcr.io/dataflow-geobeam/example-py37:latest not found: manifest unknown: Failed to fetch "latest" from request "/v2/dataflow-geobeam/example-py37/manifests/latest".. This is likely due to an invalid SDK container image URL. Please verify any provided SDK container image is valid and that Dataflow workers have permissions to pull image..```

Got the docker engine running now, and this is the type of error message I'm getting with the same attempts to pull (from my local machine):
```
➜ docker pull gcr.io/dataflow-geobeam/base
Using default tag: latest
Error response from daemon: manifest for gcr.io/dataflow-geobeam/base:latest not found: manifest unknown: Failed to fetch "latest" from request "/v2/dataflow-geobeam/base/manifests/latest"
```

**Comment by Vadoid** [comment]
Interesting, having the same issue from GCP console.

**Comment by tjwebb** [comment]
thanks for reporting, I will take a look at this today.

**Comment by tjwebb** [comment]
I have re-published the images

In the medium-term, the containers will be moving to a different repository. I will update the Dockerfiles and scripts in this repo when that happens.
