### ISSUE TITLE
Docstring type of fn.format_record is type but takes in string

### ISSUE THREAD

**Issue by jtmiclat** [GoogleCloudPlatform/dataflow-geobeam#5]
Hi! Cool project that I want to test out but I noticed an inconsistency with the docstring and the code. Not sure which should be followed.

https://github.com/GoogleCloudPlatform/dataflow-geobeam/blob/21479252be373b795a5c7d6626021b01a042e5de/geobeam/fn.py#L67-L91

The docstring should be
```
        band_type (str, optional): Default to int. The data type of the
            raster band column to store in the database.
...
        p | beam.Map(geobeam.fn.format_record,
            band_column='elev', band_type='float'
```
or the code should be 
```
def format_record(element, band_column=None, band_type=int):
    import json

    props, geom = element
    cast = band_type
```

Thanks!

**Comment by tjwebb** [comment]
Good catch, thanks! The code is correct, naturally :)
