### ISSUE TITLE
Bug: Incorrect layer parameter in geobeam.util.get_bigquery_schema_dataflow() for GDB files

### ISSUE THREAD

**Issue by Kamparia** [GoogleCloudPlatform/dataflow-geobeam#51]
**Description:**

I discovered a bug in the implementation of geobeam.util.get_bigquery_schema_dataflow() for GDB files. In the function util.py at line 133, the layer argument is mistakenly assigned the value of the gdb_name variable instead of layer_name. As a result, the function throws the following error:

`ValueError: Null layer: 'FRD_510104_Coastal_GeoDatabase_20160708.gdb' `

I have created a [pull request (#50)](https://github.com/GoogleCloudPlatform/dataflow-geobeam/pull/50) to address this issue.

Thank you.

**Comment by tjwebb** [comment]
Thanks! I'll take a look this week

**Comment by tjwebb** [comment]
Resolved by #50
